# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Domain and URL
url: https://sylvaind.me
baseurl: "" # the subpath of your site, e.g. /blog
domain-name: "sylvaind.me" # To get the prod links working local (e.g.: http://images.weserv.nl/?url={{ site.produrl }}/ )
# Site Info
title: "Sylvain Deschenes | Agile Scrum Kanban Lean"
titlemenu: "Sylvain Deschenes"
description: "Empowers teams to efficiently deliver value and innovation"
author: "Sylvain Deschenes"
keywords: "project, operation, management, coach, master, agile, scrum, kanban, lean, pmp, pspo, psm"
logo: "/img/sylvain-deschenes-rubik-logo.png"
logo-alt: "sylvain deschenes agile scrum kanban lean logo"
lang: en_CA
social:
  name: "Sylvain Deschenes"
  links:
    - https://www.linkedin.com/in/sylvaind/
    - http://github.com/sylvaindeschenes

# SEO Friendly URL for Blog Post (or Timeline entry)
# permalink: /blog/:title/
permalink: /career/:year/:title/

# Goggle Analytics Seting - The code is located in _includes/js.html and _includes/cookie-consent.html
google-tracking-id: UA-122302872-1

# Timeline Section Settings / Default career thumbnail image.
career-img: "img/timeline/default.jpg"
begenning-career-img: "img/timeline/sylvain-deschenes-profile.jpg"

# Contact Section Settings - The code is located in _layoutd/default.html
email: "contact@sylvaind.me"
address: "Enterprise, Christ Church, Barbados"
address-map-url: "https://goo.gl/maps/ftY5fRDTHx42"
# Contact form handler - The code is located in _includes/contact-form.html
contact-form-handler: "https://www.briskforms.com/go/0340497525801aac6f7824b63d103385"

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude: ["Rakefile", "LICENSE", "readme.markdown", "Gemfile", "Gemfile.lock"]

# _layouts/compress.html settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false # Set to true for debug
  profile: false
  startings: [html, head, body]